server:
  port: 9001

#数据源配置
spring:
  zipkin:
    base-url: http://192.168.6.188:9411/
    sender:
      type: web
  datasource:
    url: jdbc:mysql://192.168.6.188:3306/gmall_activity?useSSL=false&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

