server:
  port: 80

spring:
  zipkin:
    base-url: http://192.168.6.188:9411/
    sender:
      type: web

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
