server:
  port: 9002

spring:
  elasticsearch:
    rest:
      uris: http://192.168.6.188:9200
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


logging:
  level:
    tracer: trace  #打开追踪器
    org.elasticsearch: trace